Added ExomeDepth summary stats and removed hardcoded reference set
UMCUGenetics/DxNextflowWES pull request #16
Opened 2020-09-02 08:12 UTC by melferink

* Added ExomeDepth summary stats 
* Removed hardcoded reference set

2020-09-02 08:54 UTC, rernst requested changes

2020-09-02 08:54 UTC, rernst commented on WES.config
> +
Extra newline mag weg.

2020-09-02 08:54 UTC, rernst commented on WES.config
> +
Extra newline mag weg.

2020-09-02 08:54 UTC, rernst commented on WES.nf
> +    ExomeDepth(Sambamba_Merge.out.map{sample_id, bam_file, bai_file -> [analysis_id, sample_id, bam_file, bai_file]})
Output van sambamba is: `tuple(sample_id, path("${sample_id}.bam"), path("${sample_id}.bam.bai")`. De map is dus niet meer nodig.

2020-09-02 08:54 UTC, rernst commented on WES.nf
> +
Extra newline mag weg.

2020-09-02 08:54 UTC, rernst commented on WES.nf
> +        path 'UMCU_*_stats.log', emit: UMCU_exomeDepth_log
Graag ook `()` gebruiken net als overige in/outputs, en exomedepth in emit is niet nodig / dubbel. Verder heb je `{sample_id}` uit de log filename gehaald. Kan dat ook bijv vcf, xml, etc.? Graag consequent hetzelfde houden.
```
path('HC_*_stats.log', emit: HC_log)
path('UMCU_*_stats.log', emit: UMCU_log)
```

2020-09-02 08:54 UTC, rernst commented on WES.config
> +
Bij / onder ExomeDepth config zetten?

2020-09-02 08:54 UTC, rernst commented on WES.nf
> +        tuple(sample_id, path("UMCU_*_${sample_id}*.vcf"), path("HC_*_${sample_id}*.vcf"), path("${sample_id}*.xml"), path("UMCU_*_${sample_id}*.log"), path("HC_*_${sample_id}*.log"), path("UMCU_*_${
Ook voor vcf, xml, igv een apart channel maken? En log files staan er nu dubbel in.

2020-09-02 08:54 UTC, rernst commented on WES.nf
> +process CreateEDmetricsSummary {
Script heet `create_exomedepth_summary`, dus process naam: `CreateExomeDepthSummary`. En hoort het script niet thuis in de exomedepth map? Van mij mag het woord 'create' ook weg. 

En dit geldt dan ook voor tag en label.

2020-09-02 08:54 UTC, rernst commented on WES.nf
> +        path(exomedepth_files)
exomedepth_files -> exomedepth_logs

2020-09-02 08:54 UTC, rernst commented on WES.nf
> +        path("${analysis_id}_exomedepth_summary.txt")
analysis_id bestaat niet voor dit process? Moet je dan wel meegeven als input, zie bijv. MultiQC.

2020-09-02 08:54 UTC, rernst commented on assets/create_exomedepth_summary.py
> +    parser.add_argument('exomedepth_files', type=argparse.FileType('r'), nargs='*', help='Exomedepth files')
exomedepth_files -> exomedepth_logs of exomedepth_log_files

2020-09-02 08:54 UTC, rernst commented on assets/create_exomedepth_summary.py
> +    for hsmetrics_file in arguments.exomedepth_files:
hsmetrics_file?

2020-09-02 08:54 UTC, rernst commented on assets/create_exomedepth_summary.py
> +#! /usr/bin/env python
Dit script doet dus niets meer dan het 'mergen' van de log files? Dat kan ook met een cat in bash, dan kan dat direct als process in nextflow?

2020-09-03 13:56 UTC, rernst requested changes

2020-09-03 13:56 UTC, rernst commented on assets/create_exomedepth_summary.py
> +            stats_dic["TC"]+=[totalcount]
`.append()`

2020-09-03 13:56 UTC, rernst commented on assets/create_exomedepth_summary.py
> +                 )),
`,`?

2020-09-03 13:57 UTC, melferink commented on assets/create_exomedepth_summary.py
> +                 )),
Geen newline ivm Windows.

2020-09-07 15:43 UTC, rernst approved these changes

2020-09-08 13:09 UTC, rernst approved these changes

2020-09-08 14:37 UTC, merged