Feature/check contamination t66906
UMCUGenetics/DxNextflowWES pull request #28
Opened 2021-02-17 08:56 UTC by ellendejong

### What has changed?
A feature is implemented to estimate DNA contamination in WES workflow. 
Therefore, VerifyBamID2 is used. Value is added to MultiQC html.

### Why was this needed?

### Additional information
Azure backlog item: https://dev.azure.com/umcu/LAB-Bioinformatics-Genetics/_workitems/edit/63171

### To-Do before ready to review
- Complete implementation + first test with GIAB
- Test with NICU samples.
- Discuss results

2021-02-17 10:00 UTC, ellendejong commented on WES.config
> +    contamination_underestimation_factor = 0.75
I am doubting about this parameter, since it is not a resource but a default setting.
I am looking for examples in existing processes, so far didn't found any.

2021-02-19 10:52 UTC, ellendejong commented on run_nextflow_wes.sh
> +    # find -type f -not -iname 'md5sum.txt' -exec md5sum {} \; > md5sum.txt
Temp. setting so cache will stay valid. 

- [ ] Undo cache/work.zip related changes.

2021-02-23 07:29 UTC, ellendejong commented on run_nextflow_wes.sh
> +workflow_path='/home/cog/edejong2/repos/DxNextflowWES/'
temp. change

2021-02-23 07:37 UTC, ellendejong commented on WES.config
> +    python_venv_path='/hpc/diaggen/software/development/python3/'
Might need to change this path to production. (and thus create a venv in that path as well)

2021-02-23 07:38 UTC, ellendejong commented on WES.config
> +    contamination_sites_bed='/hpc/diaggen/users/ellen/references/1000g.phase3.10k.b37.exome.vcf.gz.dat.bed'
After accepting this feature implementation, these files should be migrated to a production/global place.

2021-02-23 08:04 UTC, ellendejong commented on run_nextflow_wes.sh
> +    # find -type f -not -iname 'md5sum.txt' -exec md5sum {} \; > md5sum.txt
Temp. setting so cache will stay valid.

- [ ]  Undo cache/work.zip related changes.

2021-02-23 11:21 UTC, rernst requested changes

2021-02-23 11:21 UTC, rernst commented on WES.config
> +    contamination_underestimation_factor = 0.75
If I am interpreting this setting correct, the contamination numbers are correct/adjusted with this value? Is this recommended by the developers of VerifyBamID? Is this not very much lab / data specific?

2021-02-23 11:21 UTC, rernst commented on WES.config
> +            path = "$params.outdir/contamination"
Publish the contamination data to the QC folder like all other QC tools: `$params.outdir/QC/Contamination`

2021-02-23 11:21 UTC, rernst commented on WES.config
> +    contamination_underestimation_factor = 0.75
I think multiqc is also using the uncorrected value?

2021-02-23 11:21 UTC, rernst commented on WES.config
> +    python_venv_path='/hpc/diaggen/software/development/python3/'
If we keep the python things then we should probably rename the parameter (and path) to `verify_bam_id_venv`.

2021-02-23 11:26 UTC, rernst commented
Forgot a concluding remark, I think we should just start by running verifybamid without correcting for possible under/over estimates of contamination and see what the results on our data.

2021-02-23 11:45 UTC, ellendejong commented on WES.config
> +    contamination_underestimation_factor = 0.75
Yes, MultiQC is using the 'raw' selfSM output. 
The contamination value is adjusted, I think to influence HaplotypeCaller (although not implemented here, yet) so it will not remove too much. I am not certain what the dependency is on lab / type of data.

2021-02-23 11:46 UTC, ellendejong commented on WES.config
> +    python_venv_path='/hpc/diaggen/software/development/python3/'
That depends, do we want tool specific environment even if it only contains python software? 
With general venv, it can be reused in other processes.

2021-02-23 11:47 UTC, ellendejong commented on WES.config
> +            path = "$params.outdir/contamination"
Ok.

2021-03-25 10:57 UTC, ellendejong commented on WES.config
I was doubting about increasing the time limit to 10m.. but I think its not needed for our regular diagnostics run.

2021-04-29 15:40 UTC, rernst reviewed
Paar kleine opmerkingen / vragen.

2021-04-29 15:40 UTC, rernst commented on WES.config
> +    genome_index = '/hpc/diaggen/data/databases/ref_genomes/Homo_sapiens.GRCh37.GATK.illumina/Homo_sapiens.GRCh37.GATK.illumina.fasta.fai'
Gebruik je deze ergens?

2021-04-29 15:40 UTC, rernst commented on WES.config
> +    // following resources are inside the container.
'the container' -> 'the quay.io/biocontainers/verifybamid2:2.0.1--h32f71e1_2 container'?

2021-04-29 15:40 UTC, rernst commented on assets/multiqc_config.yaml
> +            - gt: 5
Moet je dit twee keer toevoegen?

2021-04-30 06:49 UTC, ellendejong commented on assets/multiqc_config.yaml
> +            - gt: 5
Ja. 
De config is zo opgesteld dat je de header / kolomID meegeeft die je wilt voorzien van een opmaak. Met de nieuwe VerifyBamID2 toevoegen wordt er een contaminatie waarde toegevoegd aan de General Statistics (mqc-generalstats-verifybamid-FREEMIX) en onderaan de pagina een aparte VerifyBamID2 sectie, waar contaminatie waarde staat in kolom FREEMIX.

Ik had eerst enkel de mqc-generalstats-verifybamid-FREEMIX meegegeven, dat was niet voldoende.
Ik heb vervolgens niet geprobeerd om alleen FREEMIX mee te geven.

2021-04-30 08:35 UTC, rernst approved these changes

2021-04-30 08:36 UTC, merged