Feature/bafupd
UMCUGenetics/DxNextflowWES pull request #35
Opened 2021-08-19 10:57 UTC by melferink

* addition of variant calling based on a SNParray target (based on GATK 4.2.1.0)
* addition of BAF analysis based on SNParray calling VCF
* addition of UPD analysis based on SNParray calling VCF and pedigree file
* increased settings for PICARD interval for SNParray interval
* increased cpu for Exomedepth analysis

2021-08-20 07:24 UTC, FiniDG commented on WES.nf
> +    //Custom process to parse PED file and output sampleID of children with both parents.
was this pedfile parsing not in make_UPD_igv.py ?

2021-08-20 07:28 UTC, FiniDG commented
should this be added, just like in https://github.com/UMCUGenetics/DxNextflowWES/pull/33/ ?
```
        executor {
            queueSize = 1000
            pollInterval = '1min'
            queueStatInterval = '5min'
            submitRatelimit = '10sec'
        }
    }
```

2021-08-20 09:18 UTC, ellendejong requested changes
I added some comments as part of my review.
I would like to propose a meeting to discuss this pull-request regarding design choices / script flow.

2021-08-20 09:18 UTC, ellendejong commented on WES.nf
> +    UPD(ped_file, analysis_id, ParsePed.out.splitCsv().flatten(), GATK_MergeVcfs.out.map{output_name, vcf_files, vcf_idx_files -> [vcf_files]}.collect())
Can you tell me a bit more about the script flow?
Is the UPD creating a file per sample, trio, family or whole sequencing run?
I am wondering about runtime and possibilities to run processes in parallel. 
Did you consider these topics when creating the script?

2021-08-20 09:18 UTC, ellendejong commented on WES.nf
> +    BAF(GATK_MergeVcfs.out)
Since this process is calling software from another repos, I would like to see BAF included in the VersionLog.

2021-08-20 09:18 UTC, ellendejong commented on WES.nf
> +    UPD(ped_file, analysis_id, ParsePed.out.splitCsv().flatten(), GATK_MergeVcfs.out.map{output_name, vcf_files, vcf_idx_files -> [vcf_files]}.collect())
Since this process is calling software from another repos, I would like to see UPD included in the VersionLog.

2021-09-03 05:56 UTC, melferink commented on WES.nf
> +    //Custom process to parse PED file and output sampleID of children with both parents.
It is in make_UPD_igv.py, but this part has a slightly different reason;  it's here to parse all children with both parents and use those as input for make_UPD_igv.py.
make_UPD_igv.py is executed in NF for each 'propper-family' child.

2021-09-03 05:59 UTC, melferink commented on WES.config
> +    withLabel: GATK_4_2_1_0_MergeVcfs {
yes!

2021-09-03 06:31 UTC, melferink commented on WES.nf
> +process BAF {
Agree about including IGV (it's output is intended to be more generic (its a BED file), but ended up being a bit more specific to IGV use).
Not sure also about the naming conventions.. we should discuss this :)

2021-09-03 06:39 UTC, melferink commented on WES.nf
> +        tuple(output_name, path(vcf_files), path(vcf_idx_files))
Not yet (although this is rather easy to change in the UPD script which uses pyvcf).
VCF files are also not published, so only takes up tmp space during NF analysis.

We could include this if the rest of the NF is converted to .vcf.gz.

2021-09-03 07:55 UTC, melferink commented on WES.config
> +        time = '15m'
Great suggestion. withName used to give PICARD_IntervalListTools and PICARD_IntervalListToolsSNP different resources.

2021-09-03 09:06 UTC, melferink commented on WES.nf
> +    script:
Good point. Will include as python script in assets instead of in WES.nf.

2021-09-03 09:13 UTC, melferink commented on WES.nf
> +                family, sample, father, mother, sex, phenotype = ped_data
PED files have fixed colums: 
    Family ID
    Individual ID
    Paternal ID
    Maternal ID
    Sex (1=male; 2=female; other=unknown)
    Phenotype

It is assumed that a correct PED file is used as input.

Multiple trio's using the same parents is working, but maybe something to add to risks/  validation (although the same code is already being used in production)

2021-09-03 09:28 UTC, melferink commented on WES.nf
> +    ParsePed(ped_file, Sambamba_Merge.out.map{sample_id, bam_file, bai_file -> [sample_id, bam_file, bai_file]})
Changed name to ParseChildFromFullTrio for clarification:

ParseChildFromFullTrio is performed to parse the samples (child) that are from a complete trio (both parent should be known and present). Single samples, or samples without both parents should not have a UPD analysis.
Importantly:  taking into account the samples that are within the project. The PED file contains **all** samples from the entire run, and from the PED it is not known which samples are in which project. 

So yes, its specific for the UPD analysis. However, migrating the code to the UPD script is not possible because the script has ParseChildFromFullTrio as a required argument.

2021-09-03 09:39 UTC, melferink commented on WES.nf
> +    UPD(ped_file, analysis_id, ParsePed.out.splitCsv().flatten(), GATK_MergeVcfs.out.map{output_name, vcf_files, vcf_idx_files -> [vcf_files]}.collect())
See above:  UPD analysis is done per complete trio.  If multiple complete trios are present in the project they should be submitted as seperate jobs in the workflow. Resources used are therefore not dependent on the amount of complete trios.

2021-09-03 09:45 UTC, melferink commented on WES.nf
> +    BAF(GATK_MergeVcfs.out)
Excellent suggestion. Will do for UPD and BAF.

2021-09-03 09:45 UTC, melferink commented on WES.nf
> +    UPD(ped_file, analysis_id, ParsePed.out.splitCsv().flatten(), GATK_MergeVcfs.out.map{output_name, vcf_files, vcf_idx_files -> [vcf_files]}.collect())
See above

2021-09-03 13:33 UTC, melferink commented on WES.nf
> +        python ${params.baf_path}/make_BAF_igv.py ${vcf_files} ${output_name}_baf.igv
As discussed:  let's see if we can improve on this in the future.

2022-04-05 14:47 UTC, lvanoijen requested changes
Two small comments.

2022-04-15 10:28 UTC, melferink commented on WES.nf
> +    ExonCovImportBam
yes.

2022-04-22 11:10 UTC, lvanoijen approved these changes
Approved

2022-04-22 15:42 UTC, lvanoijen submitted a review, later dismissed

2022-04-25 05:58 UTC, ellendejong commented on WES.nf
> +    //cache = false  //Disable cache to force a clarity export restarting the workflow.
Is this on purpose?

2022-04-25 06:01 UTC, ellendejong commented on WES.nf
> +
Sometimes you use a single newline, and sometimes double.
Please be consistent.

2022-04-25 06:03 UTC, ellendejong commented on WES.nf
> +)
Would love to see a consistent use of newlines.

2022-04-25 09:22 UTC, ellendejong approved these changes
Previous requested changes have been resolved.

2022-04-25 09:38 UTC, merged