Feature/mosaichunter
UMCUGenetics/DxNextflowWES pull request #86
Opened 2023-10-26 11:54 UTC by BasMonkey

Added MosaiciHunter to WES Nextflow workflow

2023-11-16 07:21 UTC, melferink commented on WES.config
> +    mh_common_site_filter_bed_file = "/hpc/diaggen/users/bas/mosaictest/Dx_mosaic_project/mosaichunter/ENSEMBL_UCSC_merged_collapsed_sorted_v3_CREv2_SSv7_100bpflank_flat.bed"
Doesn't seem to be a production location.
Use Dx_tracks paths and refer to latest file including CREv4.
Include in Dx_tracks if necessary.

2023-11-16 07:24 UTC, melferink commented on WES.config
> +    mh_config_file_one = "/hpc/diaggen/users/bas/mosaictest/Dx_mosaic_project/mosaichunter/configurationfiles/exome_lh_ns_sb_parameters.conffile"
see above. Not sure about location/repo though: I would suggest DxNextflowWES/assests, but let's discuss with the others first

2023-11-16 08:58 UTC, melferink submitted a review, later dismissed
Few small comments. 
Main will be the correct production locations

2024-02-19 08:10 UTC, BasMonkey commented on WES.config
> +    mh_config_file_two = "/hpc/diaggen/users/bas/mosaictest/Dx_mosaic_project/mosaichunter/configurationfiles/exome_lh_ns_sb.conffile"
Moved to DxTracks repo

2024-02-19 08:11 UTC, BasMonkey commented on WES.config
> +    mh_common_site_filter_bed_file = "/hpc/diaggen/users/bas/mosaictest/Dx_mosaic_project/mosaichunter/ENSEMBL_UCSC_merged_collapsed_sorted_v3_CREv2_SSv7_100bpflank_flat.bed"
Moved / changed to DxTracks

2024-03-12 14:10 UTC, rernst requested changes
I think you are missing some components?

2024-03-12 14:10 UTC, rernst commented on WES.config
> +
1 empty line is enough :D

2024-03-12 14:10 UTC, rernst commented on WES.config
> +    }
Add publish dir?

2024-03-12 14:10 UTC, rernst commented on WES.nf
> +    )
Duplicate code? I think you are missing `MosaicHunterGetGender`?

2024-03-12 14:27 UTC, BasMonkey commented on WES.config
> +    }
`publishDir` is defined in the process, in order to use the `saveAs` parameter to add the `sample_id` in the saved filename. This is not be possible when `publishDir` is placed in the `WES.config` file.

2024-03-12 14:38 UTC, BasMonkey commented on WES.nf
> +    )
Whoops, fixed this!

2024-03-12 14:42 UTC, BasMonkey commented on WES.config
> +    mh_reference_file = "$params.genome"
I created this additional variable to keep the MosaicHunter module more flexible. Now a different reference_file can easily be selected specifically for MosaicHunter without having to adjust the process. But if it's better to just use `$params.genome`, I'll change it :)

2024-03-19 13:25 UTC, rernst requested changes
Nog een klein dingetje.

2024-03-19 13:25 UTC, rernst commented on WES.nf
> +        "${workflow.projectDir}$params.mh_config_file_one"
Ik zou hier voor de zekerheid altijd een `/` tussen zetten.

2024-03-19 13:25 UTC, rernst commented on WES.nf
> +        "${workflow.projectDir}$params.mh_config_file_two"
Zie hierboven.

2024-03-19 13:27 UTC, BasMonkey commented on WES.nf
> +        "${workflow.projectDir}$params.mh_config_file_one"
Toegevoegd :)

2024-03-19 13:28 UTC, BasMonkey commented on WES.nf
> +        "${workflow.projectDir}$params.mh_config_file_two"
Toegevoegd :)

2024-03-19 13:29 UTC, rernst approved these changes

2024-03-27 10:14 UTC, ellendejong approved these changes

2024-03-27 10:56 UTC, merged