Feature/nextflow upgrade 23 10 0
UMCUGenetics/DxNextflowWES pull request #89
Opened 2024-01-08 13:08 UTC by BasMonkey

• Added allow overwrites to the config so that a workflow can be restarted.
• Refactor of the in- and output variables so that the workflows can be run with Nextflow 23.10.0 (mainly in CustomModules, [See the CustomModules repo](https://github.com/UMCUGenetics/CustomModules/tree/feature/nextflow_upgrade_23_10_0))

2024-01-17 11:56 UTC, ellendejong requested changes

2024-01-17 11:56 UTC, ellendejong commented on run_nextflow_wes.sh
> +file="log/nextflow_trace.txt"
You should use full path instead.

2024-01-17 11:56 UTC, ellendejong commented on run_nextflow_wes.sh
> +    current_suffix=$(echo "$file" | grep -oE '[0-9]+$')
My personal preference: using curly brackets if variables.

2024-01-17 11:56 UTC, ellendejong commented on run_nextflow_wes.sh
> +    new_file="${file%.*}_$new_suffix.${file##*.}"
Nice, I will remember this notation. Norally I use `basename` instead, but think I would prefer this alternative :)

2024-03-06 12:42 UTC, ellendejong submitted a review, later dismissed

2024-03-08 09:20 UTC, melferink approved these changes
Ok!

2024-03-27 09:07 UTC, merged