Release/v2.1.0
UMCUGenetics/DxNextflowWES pull request #93
Opened 2024-03-27 11:01 UTC by melferink

* Upgrade Nextflow 23.10.0
* Feature MosaicHunter
* Feature GenderCheckY
* Update CustomModules
* Update NextflowModules

2024-04-02 13:23 UTC, rernst requested changes

2024-04-02 13:23 UTC, rernst commented on run_nextflow_wes.sh
> +    # Check if any trance files with a suffix exist
Small typo, although a bit of trance is always nice.

2024-04-02 13:28 UTC, BasMonkey commented on run_nextflow_wes.sh
> +    # Check if any trance files with a suffix exist
Fixed 🎵

2024-04-02 13:36 UTC, rernst submitted a review, later dismissed

2024-04-11 12:11 UTC, rernst approved these changes

2024-04-26 10:31 UTC, merged